### ISSUE TITLE
buildmake.py usage is incorrect

### ISSUE THREAD

**Issue by mquevill** [TinkerTools/Tinker#57]
In `make/0README`, the instructions say to run `./buildmake.py ../source`, but when you attempt to call this, it throws an `IsADirectoryError`. The full error message is listed below:
```python
Traceback (most recent call last):
  File "./buildmake.py", line 364, in <module>
    categorize_fortran_files(sys.argv[1:])
  File "./buildmake.py", line 271, in categorize_fortran_files
    stem, filetype, use_list = determine_module_subroutine_program(filename)
  File "./buildmake.py", line 227, in determine_module_subroutine_program
    content = [line.rstrip().lower() for line in open(fortran_filename)]
IsADirectoryError: [Errno 21] Is a directory: '../source'
```

If I am understanding this script properly, it should be run with
```shell
./buildmake.py ../source/*.f > Makefile
```

**Comment by zhi-wang** [comment]
@mquevill You are absolutely correct. The README file should have been updated.

@jayponder

**Comment by jayponder** [comment]
This is not fixed. Thanks!
